Restaurant.create!(name: "Nobu", address: "Amsterdam", phone_number: "3187937367", category: "japanese")
Restaurant.create!(name: "Breda", address: "Amsterdam", phone_number: "3187937367", category: "belgian")
Restaurant.create!(name: "Shin Ju", address: "Amsterdam", phone_number: "4487937367", category: "chinese")
Restaurant.create!(name: "Pianeta Terra", address: "Amsterdam", phone_number: "3187937367", category: "italian")
Restaurant.create!(name: "Pastis", address: "Amsterdam", phone_number: "3187937367", category: "french")
